### ISSUE TITLE
[Feature Request] Text color function

### ISSUE THREAD

**Issue by woosungchoi** [Vanessa219/vditor#677] opened 2020-08-03 05:00 UTC
The markdown editor called TOAST UI Editor has text color function.

TOAST UI Editor : https://github.com/nhn/tui.editor

color-syntax plugin : https://github.com/nhn/tui.editor/tree/master/plugins/color-syntax

It would be better if the vditor also had a text color feature.

**Comment by 88250** [comment] 2020-08-03 05:05
Duplicate of #428

**Closed by 88250** 2020-08-03 05:05 UTC
