### ISSUE TITLE
TOC problem.

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#1003] opened 2021-05-19 01:25 UTC
```
### Heading 3-1
##### Heading 5-1
##### Heading 5-2
#### Heading 4-1
#### Heading 4-2
###### Heading 6-1
###### Heading 6-2
### Heading 3-2
###### Heading 6-1
```
OK at typora
<img width="416" alt="Screen Shot 2021-05-18 at 8 20 45 PM" src="https://user-images.githubusercontent.com/15811943/118742940-fd190a00-b816-11eb-95d2-b1429b776f90.png">

But not OK at vditor
<img width="769" alt="Screen Shot 2021-05-18 at 8 20 19 PM" src="https://user-images.githubusercontent.com/15811943/118742987-13bf6100-b817-11eb-9bf9-f2841085aa49.png">

**Comment by HerbertHe** [comment] 2021-05-22 11:55
the indent of different level of heading?

**Comment by 88250** [comment] 2022-01-25 08:10
It's not too clear what the problem is, I'll close it first, thank you.

**Closed by 88250** 2022-01-25 08:10 UTC
