### ISSUE TITLE
SV mode discussion

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#568] opened 2020-07-10 22:27 UTC
I think this mode is too difficult to use.

Which points are better than IR mode?  

I think we need the original `SV` mode. (old style.)

This new mode name `Vditor Mode`

**Comment by 88250** [comment] 2020-07-11 03:10
We need time to polish the new SV mode. This mode is a "classic" usage for markdown users, so we need it at present. The old SV mode has some defects that can not be fixed caused by it not based on DOM tree, it based on a plain text, it hard to do some semantic parsing or rendering, such as replacing upload file URL, markdown syntax highlighting, etc.

The current SV mode is 'weird' for newcomers maybe, but this is where its potential lies. The goals of SV mode are:

* Let every user write standard, well-formed markdown text easily
* Intelligent writing assistant, like auto-completion in developers' IDE

At present, we need to reduce the auto format to make more 'free' for user writing, I think we are in the right direction. Nowadays, I and @Vanessa219 will discuss how to remains the original writing format user inputted as possible as we can, welcome to contribute your advice, thank you.

**Comment by jakekwak** [comment] 2020-07-11 22:41
@88250 We need this kind of GFM Spec occasionally. we can not type this spec.  it automatically converted when we copy & paste them.

1. https://github.github.com/gfm/#example-19
2. https://github.github.com/gfm/#example-25
3. empty `>` for seperate paragraph
4. https://github.github.com/gfm/#example-40
5. https://github.github.com/gfm/#example-52
6. https://github.github.com/gfm/#example-57

**Comment by 88250** [comment] 2020-07-12 03:17
@jakekwak Yes, the rendering is real-time while typing, so I think we just need test some GFM cases because other cases can not be typed in Vditor.

**Comment by Vanessa219** [comment] 2020-07-17 00:40
If you have no problems, I will close it first.

**Closed by Vanessa219** 2020-07-17 00:40 UTC

**Comment by jakekwak** [comment] 2020-07-22 22:11
@88250 Is there any way to support the old `sv` mode? If it is impossible, please let me know how to

**Comment by 88250** [comment] 2020-07-23 00:11
@jakekwak Plain text mode has some problems we have not found solutions: 

1. Accurate sync scroll between text edit area and preview area, this will be improved in `sv` mode via structured DOM node 
2. Paste content with images need to fetch and uploading images (or some else custom handing), this has been done in `sv` mode
